--SQL

--NUMBER
--NVARCHAR2

--CREATE TABLE TEST1

CREATE TABLE TEST1 (
  --COLUMN NAME COLUMN TYPE CONSTRAINT
  ID NUMBER NOT NULL,
  --
  CONSTRAINT TEST1_PK PRIMARY KEY (ID),
  SOME_TEXT NVARCHAR2(30)
  );